# Generated by Django 3.0.6 on 2020-06-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('description', models.CharField(max_length=250, verbose_name='Descrição')),
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Endereço para a API')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('shouldShow', models.BooleanField(default=True, verbose_name='Mostrar categoria ao cliente?')),
                ('image', models.ImageField(max_length=250, upload_to='images/standard_pizzeria/categories', verbose_name='Url do Ícone')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('dateRegister', models.DateTimeField(auto_now=True, null=True, verbose_name='Data do Último Registro')),
                ('description', models.CharField(max_length=250, verbose_name='Descrição')),
                ('ingredients', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ingredientes')),
                ('notes', models.CharField(blank=True, max_length=250, null=True, verbose_name='Observações')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Deixar em branco se for Pizza', max_digits=10, null=True, verbose_name='Preço (Explícito)')),
                ('size', models.CharField(blank=True, help_text='Deixar em branco se for Pizza', max_length=50, null=True, verbose_name='Tamanho (Explícito)')),
                ('shouldShow', models.BooleanField(default=True, verbose_name='Mostrar produto ao cliente?')),
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/standard_pizzeria/products', verbose_name='Url da Imagem')),
                ('category', models.ForeignKey(default='gYOBtzVcIFN01Z7R9Utx', on_delete=django.db.models.deletion.CASCADE, to='standard_backend_app.Categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição do tamanho')),
                ('flavors_quantity', models.IntegerField(default=1, verbose_name='Quantidade de Sabores')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
            ],
        ),
        migrations.CreateModel(
            name='Valore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standard_backend_app.Produto')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standard_backend_app.Tamanho')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='size_prices',
            field=models.ManyToManyField(help_text='Preço por tamanho', related_name='size', through='standard_backend_app.Valore', to='standard_backend_app.Tamanho', verbose_name='Tamanho-Preço'),
        ),
    ]
