# Generated by Django 3.0.6 on 2020-06-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Imagem'),
        ),
    ]
