# Generated by Django 3.0.6 on 2020-06-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dateTime',
            field=models.DateTimeField(blank=True, default='2020-06-25T14:32:03.244554-03:00', null=True, verbose_name='Data do Registro'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dateRegister',
            field=models.DateTimeField(blank=True, default='2020-06-25T14:32:03.161604-03:00', null=True, verbose_name='Data do Último Registro'),
        ),
    ]
