# Generated by Django 3.0.6 on 2020-06-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_backend_app', '0002_auto_20200609_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='dateRegister',
            field=models.DateTimeField(blank=True, default='2020-06-09 16:02:37', null=True, verbose_name='Data de Registro'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço (Explícito)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tamanho (Explícito)'),
        ),
    ]
