# Generated by Django 3.0.6 on 2020-06-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_backend_app', '0005_auto_20200625_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size_option',
            field=models.CharField(choices=[('withdraw', 'Retirada'), ('delivery', 'Entrega')], default='withdraw', max_length=100, verbose_name='Tamanho-Preço'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dateTime',
            field=models.DateTimeField(blank=True, default='2020-06-26T09:28:44.519579-03:00', null=True, verbose_name='Data do Registro'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dateRegister',
            field=models.DateTimeField(blank=True, default='2020-06-26T09:28:44.425652-03:00', null=True, verbose_name='Data do Último Registro'),
        ),
    ]
