# Generated by Django 3.0.6 on 2020-06-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_backend_app', '0006_auto_20200626_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size_option',
            field=models.CharField(choices=[('', '')], default='withdraw', max_length=100, verbose_name='Tamanho-Preço'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dateTime',
            field=models.DateTimeField(blank=True, default='2020-06-26T17:14:05.492042-03:00', null=True, verbose_name='Data do Registro'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dateRegister',
            field=models.DateTimeField(blank=True, default='2020-06-26T17:14:05.058324-03:00', null=True, verbose_name='Data do Último Registro'),
        ),
    ]
