# Generated by Django 3.0.6 on 2020-06-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_backend_app', '0007_auto_20200626_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size_option',
            field=models.CharField(blank=True, choices=[('', '')], default='withdraw', max_length=100, null=True, verbose_name='Tamanho-Preço'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dateTime',
            field=models.DateTimeField(blank=True, default='2020-06-27T19:03:25.087365-03:00', null=True, verbose_name='Data do Registro'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dateRegister',
            field=models.DateTimeField(blank=True, default='2020-06-27T19:03:25.006411-03:00', null=True, verbose_name='Data do Último Registro'),
        ),
    ]
