# Generated by Django 3.0.6 on 2020-06-29 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard_backend_app', '0008_auto_20200627_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='size_option',
        ),
        migrations.AddField(
            model_name='item',
            name='tamanho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='standard_backend_app.Tamanho'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dateTime',
            field=models.DateTimeField(blank=True, default='2020-06-29T11:10:17.172063-03:00', null=True, verbose_name='Data do Registro'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dateRegister',
            field=models.DateTimeField(blank=True, default='2020-06-29T11:10:17.066123-03:00', null=True, verbose_name='Data do Último Registro'),
        ),
    ]
