# Generated by Django 3.0.6 on 2020-06-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_backend_app', '0010_auto_20200630_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dateTime',
            field=models.DateTimeField(blank=True, default='2020-06-30T14:37:52.529377-03:00', null=True, verbose_name='Data do Registro'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dateRegister',
            field=models.DateTimeField(blank=True, default='2020-06-30T14:37:52.446424-03:00', null=True, verbose_name='Data do Último Registro'),
        ),
    ]
