# Generated by Django 3.0.6 on 2020-06-30 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard_backend_app', '0011_auto_20200630_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standard_backend_app.Pedido'),
        ),
        migrations.AlterField(
            model_name='item',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standard_backend_app.Produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dateTime',
            field=models.DateTimeField(blank=True, default='2020-06-30T14:43:55.492910-03:00', null=True, verbose_name='Data do Registro'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dateRegister',
            field=models.DateTimeField(blank=True, default='2020-06-30T14:43:55.149419-03:00', null=True, verbose_name='Data do Último Registro'),
        ),
    ]
