"""
Django settings for pizzeria_standard_ws project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import environ

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

env = environ.Env(
    DEBUG=(bool, False),
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rcrggyn(9!l-rzu26w4v1+wvl-a5vhbi=k+hjs*r3jmz^d0a9$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'standard_backend_app.apps.PizzariaStandardWsProjectConfig',
    'pandras_homepage.apps.PandrasHomepageConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pizzeria_standard_ws.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Enable {{ STATIC_URL }} and {{ MEDIA_URL }}
                'django.template.context_processors.media',
                'django.template.context_processors.static',
            ],
            # 'loaders':[
            #     'django.template.loaders.filesystem.Loader',
            # ]
        },
    },
]

WSGI_APPLICATION = 'pizzeria_standard_ws.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    # 'default': {'ENGINE': 'django.db.backends.mysql'},
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        'ENGINE': 'django.db.backends.mysql',
        # 'NAME': os.path.join(BASE_DIR, 'db.standard'),
        'NAME': 'standard_project',
        'USER': 'root',
        'PASSWORD': 'admin',
    },
    'standard': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'standard_project',
        'USER': 'root',
        'PASSWORD': 'admin',
    },
    'dom_marino': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dom_marino',
        'USER': 'root',
        'PASSWORD': 'admin',
    },

    'pandras': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pandras',
        'USER': 'root',
        'PASSWORD': 'admin',
    },
    # 'adminNeto': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'kingticom_oca639',
    #     'HOST': '144.217.28.12',
    #     'PORT': '3303',
    #     'USER': 'kingticom_oca639',
    #     'PASSWORD': 'tst.2020.app'
    # }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_ROOT = ''
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR, os.path.join('pandras_homepage/templates/'),
    BASE_DIR, os.path.join('/media/'), BASE_DIR, os.path.join('/static/')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
# GOOGLE_APPLICATION_CREDENTIALS = os.path.join(
#     BASE_DIR,
#     env('GOOGLE_APPLICATION_CREDENTIALS'),
# )